#:kivy 2.2.0

#: include screenmain.kv
#: include screenmoves.kv
#: include screeneditsituation.kv
#: include screeninputfilename.kv
#: include screenmergexqf.kv
#: include screeninfo.kv

MDScreenManager:
    ScreenMain:
        id: id_screenmain
    ScreenMoves:
        id: id_screenmoves
    ScreenEditSituation:
        id: id_screditsituiation
    ScreenInputFileName:
        id: id_scrinputfilename
    ScreenMergeXQF:
        id:id_screenmergexqf
    ScreenInfo:
        id:id_screeninfo
